/* Autogenerated by png2wx.pl on Fri Oct 25 16:20:08 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_RTZroute_pi;
extern wxBitmap *_img_RTZroute;

#ifdef ocpnUSE_SVG
extern wxString _svg_RTZroute;
extern wxString _svg_RTZroute_toggled;
#endif

#endif /* ICONS_H */
